// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cashavail.proto

package com.drifai.grpc;

public final class Cashavail {
  private Cashavail() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CashAvailRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CashAvailRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string fundId = 1;</code>
     */
    java.lang.String getFundId();
    /**
     * <code>string fundId = 1;</code>
     */
    com.google.protobuf.ByteString
        getFundIdBytes();

    /**
     * <code>string cashAvailType = 2;</code>
     */
    java.lang.String getCashAvailType();
    /**
     * <code>string cashAvailType = 2;</code>
     */
    com.google.protobuf.ByteString
        getCashAvailTypeBytes();

    /**
     * <code>string cashAvailSubType = 3;</code>
     */
    java.lang.String getCashAvailSubType();
    /**
     * <code>string cashAvailSubType = 3;</code>
     */
    com.google.protobuf.ByteString
        getCashAvailSubTypeBytes();

    /**
     * <code>string currency = 4;</code>
     */
    java.lang.String getCurrency();
    /**
     * <code>string currency = 4;</code>
     */
    com.google.protobuf.ByteString
        getCurrencyBytes();
  }
  /**
   * Protobuf type {@code CashAvailRequest}
   */
  public  static final class CashAvailRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CashAvailRequest)
      CashAvailRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CashAvailRequest.newBuilder() to construct.
    private CashAvailRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CashAvailRequest() {
      fundId_ = "";
      cashAvailType_ = "";
      cashAvailSubType_ = "";
      currency_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CashAvailRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              fundId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              cashAvailType_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              cashAvailSubType_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              currency_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.drifai.grpc.Cashavail.internal_static_CashAvailRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.drifai.grpc.Cashavail.internal_static_CashAvailRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.drifai.grpc.Cashavail.CashAvailRequest.class, com.drifai.grpc.Cashavail.CashAvailRequest.Builder.class);
    }

    public static final int FUNDID_FIELD_NUMBER = 1;
    private volatile java.lang.Object fundId_;
    /**
     * <code>string fundId = 1;</code>
     */
    public java.lang.String getFundId() {
      java.lang.Object ref = fundId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fundId_ = s;
        return s;
      }
    }
    /**
     * <code>string fundId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFundIdBytes() {
      java.lang.Object ref = fundId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fundId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CASHAVAILTYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object cashAvailType_;
    /**
     * <code>string cashAvailType = 2;</code>
     */
    public java.lang.String getCashAvailType() {
      java.lang.Object ref = cashAvailType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cashAvailType_ = s;
        return s;
      }
    }
    /**
     * <code>string cashAvailType = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCashAvailTypeBytes() {
      java.lang.Object ref = cashAvailType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cashAvailType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CASHAVAILSUBTYPE_FIELD_NUMBER = 3;
    private volatile java.lang.Object cashAvailSubType_;
    /**
     * <code>string cashAvailSubType = 3;</code>
     */
    public java.lang.String getCashAvailSubType() {
      java.lang.Object ref = cashAvailSubType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cashAvailSubType_ = s;
        return s;
      }
    }
    /**
     * <code>string cashAvailSubType = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCashAvailSubTypeBytes() {
      java.lang.Object ref = cashAvailSubType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cashAvailSubType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CURRENCY_FIELD_NUMBER = 4;
    private volatile java.lang.Object currency_;
    /**
     * <code>string currency = 4;</code>
     */
    public java.lang.String getCurrency() {
      java.lang.Object ref = currency_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currency_ = s;
        return s;
      }
    }
    /**
     * <code>string currency = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCurrencyBytes() {
      java.lang.Object ref = currency_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFundIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fundId_);
      }
      if (!getCashAvailTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cashAvailType_);
      }
      if (!getCashAvailSubTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cashAvailSubType_);
      }
      if (!getCurrencyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, currency_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFundIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fundId_);
      }
      if (!getCashAvailTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cashAvailType_);
      }
      if (!getCashAvailSubTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, cashAvailSubType_);
      }
      if (!getCurrencyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, currency_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.drifai.grpc.Cashavail.CashAvailRequest)) {
        return super.equals(obj);
      }
      com.drifai.grpc.Cashavail.CashAvailRequest other = (com.drifai.grpc.Cashavail.CashAvailRequest) obj;

      boolean result = true;
      result = result && getFundId()
          .equals(other.getFundId());
      result = result && getCashAvailType()
          .equals(other.getCashAvailType());
      result = result && getCashAvailSubType()
          .equals(other.getCashAvailSubType());
      result = result && getCurrency()
          .equals(other.getCurrency());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FUNDID_FIELD_NUMBER;
      hash = (53 * hash) + getFundId().hashCode();
      hash = (37 * hash) + CASHAVAILTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getCashAvailType().hashCode();
      hash = (37 * hash) + CASHAVAILSUBTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getCashAvailSubType().hashCode();
      hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
      hash = (53 * hash) + getCurrency().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.drifai.grpc.Cashavail.CashAvailRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.drifai.grpc.Cashavail.CashAvailRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.drifai.grpc.Cashavail.CashAvailRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.drifai.grpc.Cashavail.CashAvailRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.drifai.grpc.Cashavail.CashAvailRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.drifai.grpc.Cashavail.CashAvailRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.drifai.grpc.Cashavail.CashAvailRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.drifai.grpc.Cashavail.CashAvailRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.drifai.grpc.Cashavail.CashAvailRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.drifai.grpc.Cashavail.CashAvailRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.drifai.grpc.Cashavail.CashAvailRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.drifai.grpc.Cashavail.CashAvailRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.drifai.grpc.Cashavail.CashAvailRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CashAvailRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CashAvailRequest)
        com.drifai.grpc.Cashavail.CashAvailRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.drifai.grpc.Cashavail.internal_static_CashAvailRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.drifai.grpc.Cashavail.internal_static_CashAvailRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.drifai.grpc.Cashavail.CashAvailRequest.class, com.drifai.grpc.Cashavail.CashAvailRequest.Builder.class);
      }

      // Construct using com.drifai.grpc.Cashavail.CashAvailRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        fundId_ = "";

        cashAvailType_ = "";

        cashAvailSubType_ = "";

        currency_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.drifai.grpc.Cashavail.internal_static_CashAvailRequest_descriptor;
      }

      @java.lang.Override
      public com.drifai.grpc.Cashavail.CashAvailRequest getDefaultInstanceForType() {
        return com.drifai.grpc.Cashavail.CashAvailRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.drifai.grpc.Cashavail.CashAvailRequest build() {
        com.drifai.grpc.Cashavail.CashAvailRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.drifai.grpc.Cashavail.CashAvailRequest buildPartial() {
        com.drifai.grpc.Cashavail.CashAvailRequest result = new com.drifai.grpc.Cashavail.CashAvailRequest(this);
        result.fundId_ = fundId_;
        result.cashAvailType_ = cashAvailType_;
        result.cashAvailSubType_ = cashAvailSubType_;
        result.currency_ = currency_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.drifai.grpc.Cashavail.CashAvailRequest) {
          return mergeFrom((com.drifai.grpc.Cashavail.CashAvailRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.drifai.grpc.Cashavail.CashAvailRequest other) {
        if (other == com.drifai.grpc.Cashavail.CashAvailRequest.getDefaultInstance()) return this;
        if (!other.getFundId().isEmpty()) {
          fundId_ = other.fundId_;
          onChanged();
        }
        if (!other.getCashAvailType().isEmpty()) {
          cashAvailType_ = other.cashAvailType_;
          onChanged();
        }
        if (!other.getCashAvailSubType().isEmpty()) {
          cashAvailSubType_ = other.cashAvailSubType_;
          onChanged();
        }
        if (!other.getCurrency().isEmpty()) {
          currency_ = other.currency_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.drifai.grpc.Cashavail.CashAvailRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.drifai.grpc.Cashavail.CashAvailRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object fundId_ = "";
      /**
       * <code>string fundId = 1;</code>
       */
      public java.lang.String getFundId() {
        java.lang.Object ref = fundId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fundId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fundId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFundIdBytes() {
        java.lang.Object ref = fundId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fundId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fundId = 1;</code>
       */
      public Builder setFundId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fundId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fundId = 1;</code>
       */
      public Builder clearFundId() {
        
        fundId_ = getDefaultInstance().getFundId();
        onChanged();
        return this;
      }
      /**
       * <code>string fundId = 1;</code>
       */
      public Builder setFundIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fundId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cashAvailType_ = "";
      /**
       * <code>string cashAvailType = 2;</code>
       */
      public java.lang.String getCashAvailType() {
        java.lang.Object ref = cashAvailType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cashAvailType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cashAvailType = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCashAvailTypeBytes() {
        java.lang.Object ref = cashAvailType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cashAvailType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cashAvailType = 2;</code>
       */
      public Builder setCashAvailType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cashAvailType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cashAvailType = 2;</code>
       */
      public Builder clearCashAvailType() {
        
        cashAvailType_ = getDefaultInstance().getCashAvailType();
        onChanged();
        return this;
      }
      /**
       * <code>string cashAvailType = 2;</code>
       */
      public Builder setCashAvailTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cashAvailType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cashAvailSubType_ = "";
      /**
       * <code>string cashAvailSubType = 3;</code>
       */
      public java.lang.String getCashAvailSubType() {
        java.lang.Object ref = cashAvailSubType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cashAvailSubType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cashAvailSubType = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCashAvailSubTypeBytes() {
        java.lang.Object ref = cashAvailSubType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cashAvailSubType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cashAvailSubType = 3;</code>
       */
      public Builder setCashAvailSubType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cashAvailSubType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cashAvailSubType = 3;</code>
       */
      public Builder clearCashAvailSubType() {
        
        cashAvailSubType_ = getDefaultInstance().getCashAvailSubType();
        onChanged();
        return this;
      }
      /**
       * <code>string cashAvailSubType = 3;</code>
       */
      public Builder setCashAvailSubTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cashAvailSubType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object currency_ = "";
      /**
       * <code>string currency = 4;</code>
       */
      public java.lang.String getCurrency() {
        java.lang.Object ref = currency_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currency_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currency = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCurrencyBytes() {
        java.lang.Object ref = currency_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currency_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currency = 4;</code>
       */
      public Builder setCurrency(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currency_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string currency = 4;</code>
       */
      public Builder clearCurrency() {
        
        currency_ = getDefaultInstance().getCurrency();
        onChanged();
        return this;
      }
      /**
       * <code>string currency = 4;</code>
       */
      public Builder setCurrencyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currency_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CashAvailRequest)
    }

    // @@protoc_insertion_point(class_scope:CashAvailRequest)
    private static final com.drifai.grpc.Cashavail.CashAvailRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.drifai.grpc.Cashavail.CashAvailRequest();
    }

    public static com.drifai.grpc.Cashavail.CashAvailRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CashAvailRequest>
        PARSER = new com.google.protobuf.AbstractParser<CashAvailRequest>() {
      @java.lang.Override
      public CashAvailRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CashAvailRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CashAvailRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CashAvailRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.drifai.grpc.Cashavail.CashAvailRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface APIResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:APIResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string clientId = 1;</code>
     */
    java.lang.String getClientId();
    /**
     * <code>string clientId = 1;</code>
     */
    com.google.protobuf.ByteString
        getClientIdBytes();

    /**
     * <code>string fundId = 2;</code>
     */
    java.lang.String getFundId();
    /**
     * <code>string fundId = 2;</code>
     */
    com.google.protobuf.ByteString
        getFundIdBytes();

    /**
     * <code>string cashAvailType = 3;</code>
     */
    java.lang.String getCashAvailType();
    /**
     * <code>string cashAvailType = 3;</code>
     */
    com.google.protobuf.ByteString
        getCashAvailTypeBytes();

    /**
     * <code>string cashAvailSubType = 4;</code>
     */
    java.lang.String getCashAvailSubType();
    /**
     * <code>string cashAvailSubType = 4;</code>
     */
    com.google.protobuf.ByteString
        getCashAvailSubTypeBytes();

    /**
     * <code>string knowledgeDate = 5;</code>
     */
    java.lang.String getKnowledgeDate();
    /**
     * <code>string knowledgeDate = 5;</code>
     */
    com.google.protobuf.ByteString
        getKnowledgeDateBytes();

    /**
     * <code>string effectiveDate = 6;</code>
     */
    java.lang.String getEffectiveDate();
    /**
     * <code>string effectiveDate = 6;</code>
     */
    com.google.protobuf.ByteString
        getEffectiveDateBytes();

    /**
     * <code>string currency = 7;</code>
     */
    java.lang.String getCurrency();
    /**
     * <code>string currency = 7;</code>
     */
    com.google.protobuf.ByteString
        getCurrencyBytes();

    /**
     * <code>double amount = 8;</code>
     */
    double getAmount();
  }
  /**
   * Protobuf type {@code APIResponse}
   */
  public  static final class APIResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:APIResponse)
      APIResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use APIResponse.newBuilder() to construct.
    private APIResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private APIResponse() {
      clientId_ = "";
      fundId_ = "";
      cashAvailType_ = "";
      cashAvailSubType_ = "";
      knowledgeDate_ = "";
      effectiveDate_ = "";
      currency_ = "";
      amount_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private APIResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              clientId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              fundId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              cashAvailType_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              cashAvailSubType_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              knowledgeDate_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              effectiveDate_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              currency_ = s;
              break;
            }
            case 65: {

              amount_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.drifai.grpc.Cashavail.internal_static_APIResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.drifai.grpc.Cashavail.internal_static_APIResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.drifai.grpc.Cashavail.APIResponse.class, com.drifai.grpc.Cashavail.APIResponse.Builder.class);
    }

    public static final int CLIENTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object clientId_;
    /**
     * <code>string clientId = 1;</code>
     */
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      }
    }
    /**
     * <code>string clientId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FUNDID_FIELD_NUMBER = 2;
    private volatile java.lang.Object fundId_;
    /**
     * <code>string fundId = 2;</code>
     */
    public java.lang.String getFundId() {
      java.lang.Object ref = fundId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fundId_ = s;
        return s;
      }
    }
    /**
     * <code>string fundId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFundIdBytes() {
      java.lang.Object ref = fundId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fundId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CASHAVAILTYPE_FIELD_NUMBER = 3;
    private volatile java.lang.Object cashAvailType_;
    /**
     * <code>string cashAvailType = 3;</code>
     */
    public java.lang.String getCashAvailType() {
      java.lang.Object ref = cashAvailType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cashAvailType_ = s;
        return s;
      }
    }
    /**
     * <code>string cashAvailType = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCashAvailTypeBytes() {
      java.lang.Object ref = cashAvailType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cashAvailType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CASHAVAILSUBTYPE_FIELD_NUMBER = 4;
    private volatile java.lang.Object cashAvailSubType_;
    /**
     * <code>string cashAvailSubType = 4;</code>
     */
    public java.lang.String getCashAvailSubType() {
      java.lang.Object ref = cashAvailSubType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cashAvailSubType_ = s;
        return s;
      }
    }
    /**
     * <code>string cashAvailSubType = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCashAvailSubTypeBytes() {
      java.lang.Object ref = cashAvailSubType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cashAvailSubType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KNOWLEDGEDATE_FIELD_NUMBER = 5;
    private volatile java.lang.Object knowledgeDate_;
    /**
     * <code>string knowledgeDate = 5;</code>
     */
    public java.lang.String getKnowledgeDate() {
      java.lang.Object ref = knowledgeDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        knowledgeDate_ = s;
        return s;
      }
    }
    /**
     * <code>string knowledgeDate = 5;</code>
     */
    public com.google.protobuf.ByteString
        getKnowledgeDateBytes() {
      java.lang.Object ref = knowledgeDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        knowledgeDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EFFECTIVEDATE_FIELD_NUMBER = 6;
    private volatile java.lang.Object effectiveDate_;
    /**
     * <code>string effectiveDate = 6;</code>
     */
    public java.lang.String getEffectiveDate() {
      java.lang.Object ref = effectiveDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        effectiveDate_ = s;
        return s;
      }
    }
    /**
     * <code>string effectiveDate = 6;</code>
     */
    public com.google.protobuf.ByteString
        getEffectiveDateBytes() {
      java.lang.Object ref = effectiveDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        effectiveDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CURRENCY_FIELD_NUMBER = 7;
    private volatile java.lang.Object currency_;
    /**
     * <code>string currency = 7;</code>
     */
    public java.lang.String getCurrency() {
      java.lang.Object ref = currency_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currency_ = s;
        return s;
      }
    }
    /**
     * <code>string currency = 7;</code>
     */
    public com.google.protobuf.ByteString
        getCurrencyBytes() {
      java.lang.Object ref = currency_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 8;
    private double amount_;
    /**
     * <code>double amount = 8;</code>
     */
    public double getAmount() {
      return amount_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getClientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientId_);
      }
      if (!getFundIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fundId_);
      }
      if (!getCashAvailTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cashAvailType_);
      }
      if (!getCashAvailSubTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, cashAvailSubType_);
      }
      if (!getKnowledgeDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, knowledgeDate_);
      }
      if (!getEffectiveDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, effectiveDate_);
      }
      if (!getCurrencyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, currency_);
      }
      if (amount_ != 0D) {
        output.writeDouble(8, amount_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getClientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientId_);
      }
      if (!getFundIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fundId_);
      }
      if (!getCashAvailTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, cashAvailType_);
      }
      if (!getCashAvailSubTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, cashAvailSubType_);
      }
      if (!getKnowledgeDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, knowledgeDate_);
      }
      if (!getEffectiveDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, effectiveDate_);
      }
      if (!getCurrencyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, currency_);
      }
      if (amount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, amount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.drifai.grpc.Cashavail.APIResponse)) {
        return super.equals(obj);
      }
      com.drifai.grpc.Cashavail.APIResponse other = (com.drifai.grpc.Cashavail.APIResponse) obj;

      boolean result = true;
      result = result && getClientId()
          .equals(other.getClientId());
      result = result && getFundId()
          .equals(other.getFundId());
      result = result && getCashAvailType()
          .equals(other.getCashAvailType());
      result = result && getCashAvailSubType()
          .equals(other.getCashAvailSubType());
      result = result && getKnowledgeDate()
          .equals(other.getKnowledgeDate());
      result = result && getEffectiveDate()
          .equals(other.getEffectiveDate());
      result = result && getCurrency()
          .equals(other.getCurrency());
      result = result && (
          java.lang.Double.doubleToLongBits(getAmount())
          == java.lang.Double.doubleToLongBits(
              other.getAmount()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + getClientId().hashCode();
      hash = (37 * hash) + FUNDID_FIELD_NUMBER;
      hash = (53 * hash) + getFundId().hashCode();
      hash = (37 * hash) + CASHAVAILTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getCashAvailType().hashCode();
      hash = (37 * hash) + CASHAVAILSUBTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getCashAvailSubType().hashCode();
      hash = (37 * hash) + KNOWLEDGEDATE_FIELD_NUMBER;
      hash = (53 * hash) + getKnowledgeDate().hashCode();
      hash = (37 * hash) + EFFECTIVEDATE_FIELD_NUMBER;
      hash = (53 * hash) + getEffectiveDate().hashCode();
      hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
      hash = (53 * hash) + getCurrency().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAmount()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.drifai.grpc.Cashavail.APIResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.drifai.grpc.Cashavail.APIResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.drifai.grpc.Cashavail.APIResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.drifai.grpc.Cashavail.APIResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.drifai.grpc.Cashavail.APIResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.drifai.grpc.Cashavail.APIResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.drifai.grpc.Cashavail.APIResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.drifai.grpc.Cashavail.APIResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.drifai.grpc.Cashavail.APIResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.drifai.grpc.Cashavail.APIResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.drifai.grpc.Cashavail.APIResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.drifai.grpc.Cashavail.APIResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.drifai.grpc.Cashavail.APIResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code APIResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:APIResponse)
        com.drifai.grpc.Cashavail.APIResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.drifai.grpc.Cashavail.internal_static_APIResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.drifai.grpc.Cashavail.internal_static_APIResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.drifai.grpc.Cashavail.APIResponse.class, com.drifai.grpc.Cashavail.APIResponse.Builder.class);
      }

      // Construct using com.drifai.grpc.Cashavail.APIResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        clientId_ = "";

        fundId_ = "";

        cashAvailType_ = "";

        cashAvailSubType_ = "";

        knowledgeDate_ = "";

        effectiveDate_ = "";

        currency_ = "";

        amount_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.drifai.grpc.Cashavail.internal_static_APIResponse_descriptor;
      }

      @java.lang.Override
      public com.drifai.grpc.Cashavail.APIResponse getDefaultInstanceForType() {
        return com.drifai.grpc.Cashavail.APIResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.drifai.grpc.Cashavail.APIResponse build() {
        com.drifai.grpc.Cashavail.APIResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.drifai.grpc.Cashavail.APIResponse buildPartial() {
        com.drifai.grpc.Cashavail.APIResponse result = new com.drifai.grpc.Cashavail.APIResponse(this);
        result.clientId_ = clientId_;
        result.fundId_ = fundId_;
        result.cashAvailType_ = cashAvailType_;
        result.cashAvailSubType_ = cashAvailSubType_;
        result.knowledgeDate_ = knowledgeDate_;
        result.effectiveDate_ = effectiveDate_;
        result.currency_ = currency_;
        result.amount_ = amount_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.drifai.grpc.Cashavail.APIResponse) {
          return mergeFrom((com.drifai.grpc.Cashavail.APIResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.drifai.grpc.Cashavail.APIResponse other) {
        if (other == com.drifai.grpc.Cashavail.APIResponse.getDefaultInstance()) return this;
        if (!other.getClientId().isEmpty()) {
          clientId_ = other.clientId_;
          onChanged();
        }
        if (!other.getFundId().isEmpty()) {
          fundId_ = other.fundId_;
          onChanged();
        }
        if (!other.getCashAvailType().isEmpty()) {
          cashAvailType_ = other.cashAvailType_;
          onChanged();
        }
        if (!other.getCashAvailSubType().isEmpty()) {
          cashAvailSubType_ = other.cashAvailSubType_;
          onChanged();
        }
        if (!other.getKnowledgeDate().isEmpty()) {
          knowledgeDate_ = other.knowledgeDate_;
          onChanged();
        }
        if (!other.getEffectiveDate().isEmpty()) {
          effectiveDate_ = other.effectiveDate_;
          onChanged();
        }
        if (!other.getCurrency().isEmpty()) {
          currency_ = other.currency_;
          onChanged();
        }
        if (other.getAmount() != 0D) {
          setAmount(other.getAmount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.drifai.grpc.Cashavail.APIResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.drifai.grpc.Cashavail.APIResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object clientId_ = "";
      /**
       * <code>string clientId = 1;</code>
       */
      public java.lang.String getClientId() {
        java.lang.Object ref = clientId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string clientId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        java.lang.Object ref = clientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string clientId = 1;</code>
       */
      public Builder setClientId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string clientId = 1;</code>
       */
      public Builder clearClientId() {
        
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }
      /**
       * <code>string clientId = 1;</code>
       */
      public Builder setClientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object fundId_ = "";
      /**
       * <code>string fundId = 2;</code>
       */
      public java.lang.String getFundId() {
        java.lang.Object ref = fundId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fundId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fundId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFundIdBytes() {
        java.lang.Object ref = fundId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fundId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fundId = 2;</code>
       */
      public Builder setFundId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fundId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fundId = 2;</code>
       */
      public Builder clearFundId() {
        
        fundId_ = getDefaultInstance().getFundId();
        onChanged();
        return this;
      }
      /**
       * <code>string fundId = 2;</code>
       */
      public Builder setFundIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fundId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cashAvailType_ = "";
      /**
       * <code>string cashAvailType = 3;</code>
       */
      public java.lang.String getCashAvailType() {
        java.lang.Object ref = cashAvailType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cashAvailType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cashAvailType = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCashAvailTypeBytes() {
        java.lang.Object ref = cashAvailType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cashAvailType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cashAvailType = 3;</code>
       */
      public Builder setCashAvailType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cashAvailType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cashAvailType = 3;</code>
       */
      public Builder clearCashAvailType() {
        
        cashAvailType_ = getDefaultInstance().getCashAvailType();
        onChanged();
        return this;
      }
      /**
       * <code>string cashAvailType = 3;</code>
       */
      public Builder setCashAvailTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cashAvailType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cashAvailSubType_ = "";
      /**
       * <code>string cashAvailSubType = 4;</code>
       */
      public java.lang.String getCashAvailSubType() {
        java.lang.Object ref = cashAvailSubType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cashAvailSubType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cashAvailSubType = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCashAvailSubTypeBytes() {
        java.lang.Object ref = cashAvailSubType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cashAvailSubType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cashAvailSubType = 4;</code>
       */
      public Builder setCashAvailSubType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cashAvailSubType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cashAvailSubType = 4;</code>
       */
      public Builder clearCashAvailSubType() {
        
        cashAvailSubType_ = getDefaultInstance().getCashAvailSubType();
        onChanged();
        return this;
      }
      /**
       * <code>string cashAvailSubType = 4;</code>
       */
      public Builder setCashAvailSubTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cashAvailSubType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object knowledgeDate_ = "";
      /**
       * <code>string knowledgeDate = 5;</code>
       */
      public java.lang.String getKnowledgeDate() {
        java.lang.Object ref = knowledgeDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          knowledgeDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string knowledgeDate = 5;</code>
       */
      public com.google.protobuf.ByteString
          getKnowledgeDateBytes() {
        java.lang.Object ref = knowledgeDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          knowledgeDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string knowledgeDate = 5;</code>
       */
      public Builder setKnowledgeDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        knowledgeDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string knowledgeDate = 5;</code>
       */
      public Builder clearKnowledgeDate() {
        
        knowledgeDate_ = getDefaultInstance().getKnowledgeDate();
        onChanged();
        return this;
      }
      /**
       * <code>string knowledgeDate = 5;</code>
       */
      public Builder setKnowledgeDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        knowledgeDate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object effectiveDate_ = "";
      /**
       * <code>string effectiveDate = 6;</code>
       */
      public java.lang.String getEffectiveDate() {
        java.lang.Object ref = effectiveDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          effectiveDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string effectiveDate = 6;</code>
       */
      public com.google.protobuf.ByteString
          getEffectiveDateBytes() {
        java.lang.Object ref = effectiveDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          effectiveDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string effectiveDate = 6;</code>
       */
      public Builder setEffectiveDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        effectiveDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string effectiveDate = 6;</code>
       */
      public Builder clearEffectiveDate() {
        
        effectiveDate_ = getDefaultInstance().getEffectiveDate();
        onChanged();
        return this;
      }
      /**
       * <code>string effectiveDate = 6;</code>
       */
      public Builder setEffectiveDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        effectiveDate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object currency_ = "";
      /**
       * <code>string currency = 7;</code>
       */
      public java.lang.String getCurrency() {
        java.lang.Object ref = currency_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currency_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currency = 7;</code>
       */
      public com.google.protobuf.ByteString
          getCurrencyBytes() {
        java.lang.Object ref = currency_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currency_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currency = 7;</code>
       */
      public Builder setCurrency(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currency_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string currency = 7;</code>
       */
      public Builder clearCurrency() {
        
        currency_ = getDefaultInstance().getCurrency();
        onChanged();
        return this;
      }
      /**
       * <code>string currency = 7;</code>
       */
      public Builder setCurrencyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currency_ = value;
        onChanged();
        return this;
      }

      private double amount_ ;
      /**
       * <code>double amount = 8;</code>
       */
      public double getAmount() {
        return amount_;
      }
      /**
       * <code>double amount = 8;</code>
       */
      public Builder setAmount(double value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double amount = 8;</code>
       */
      public Builder clearAmount() {
        
        amount_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:APIResponse)
    }

    // @@protoc_insertion_point(class_scope:APIResponse)
    private static final com.drifai.grpc.Cashavail.APIResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.drifai.grpc.Cashavail.APIResponse();
    }

    public static com.drifai.grpc.Cashavail.APIResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<APIResponse>
        PARSER = new com.google.protobuf.AbstractParser<APIResponse>() {
      @java.lang.Override
      public APIResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new APIResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<APIResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<APIResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.drifai.grpc.Cashavail.APIResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Empty)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code Empty}
   */
  public  static final class Empty extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Empty)
      EmptyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Empty.newBuilder() to construct.
    private Empty(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Empty() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Empty(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.drifai.grpc.Cashavail.internal_static_Empty_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.drifai.grpc.Cashavail.internal_static_Empty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.drifai.grpc.Cashavail.Empty.class, com.drifai.grpc.Cashavail.Empty.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.drifai.grpc.Cashavail.Empty)) {
        return super.equals(obj);
      }
      com.drifai.grpc.Cashavail.Empty other = (com.drifai.grpc.Cashavail.Empty) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.drifai.grpc.Cashavail.Empty parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.drifai.grpc.Cashavail.Empty parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.drifai.grpc.Cashavail.Empty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.drifai.grpc.Cashavail.Empty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.drifai.grpc.Cashavail.Empty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.drifai.grpc.Cashavail.Empty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.drifai.grpc.Cashavail.Empty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.drifai.grpc.Cashavail.Empty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.drifai.grpc.Cashavail.Empty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.drifai.grpc.Cashavail.Empty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.drifai.grpc.Cashavail.Empty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.drifai.grpc.Cashavail.Empty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.drifai.grpc.Cashavail.Empty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Empty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Empty)
        com.drifai.grpc.Cashavail.EmptyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.drifai.grpc.Cashavail.internal_static_Empty_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.drifai.grpc.Cashavail.internal_static_Empty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.drifai.grpc.Cashavail.Empty.class, com.drifai.grpc.Cashavail.Empty.Builder.class);
      }

      // Construct using com.drifai.grpc.Cashavail.Empty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.drifai.grpc.Cashavail.internal_static_Empty_descriptor;
      }

      @java.lang.Override
      public com.drifai.grpc.Cashavail.Empty getDefaultInstanceForType() {
        return com.drifai.grpc.Cashavail.Empty.getDefaultInstance();
      }

      @java.lang.Override
      public com.drifai.grpc.Cashavail.Empty build() {
        com.drifai.grpc.Cashavail.Empty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.drifai.grpc.Cashavail.Empty buildPartial() {
        com.drifai.grpc.Cashavail.Empty result = new com.drifai.grpc.Cashavail.Empty(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.drifai.grpc.Cashavail.Empty) {
          return mergeFrom((com.drifai.grpc.Cashavail.Empty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.drifai.grpc.Cashavail.Empty other) {
        if (other == com.drifai.grpc.Cashavail.Empty.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.drifai.grpc.Cashavail.Empty parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.drifai.grpc.Cashavail.Empty) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Empty)
    }

    // @@protoc_insertion_point(class_scope:Empty)
    private static final com.drifai.grpc.Cashavail.Empty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.drifai.grpc.Cashavail.Empty();
    }

    public static com.drifai.grpc.Cashavail.Empty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Empty>
        PARSER = new com.google.protobuf.AbstractParser<Empty>() {
      @java.lang.Override
      public Empty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Empty(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Empty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Empty> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.drifai.grpc.Cashavail.Empty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CashAvailRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CashAvailRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_APIResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_APIResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017cashavail.proto\"e\n\020CashAvailRequest\022\016\n" +
      "\006fundId\030\001 \001(\t\022\025\n\rcashAvailType\030\002 \001(\t\022\030\n\020" +
      "cashAvailSubType\030\003 \001(\t\022\020\n\010currency\030\004 \001(\t" +
      "\"\260\001\n\013APIResponse\022\020\n\010clientId\030\001 \001(\t\022\016\n\006fu" +
      "ndId\030\002 \001(\t\022\025\n\rcashAvailType\030\003 \001(\t\022\030\n\020cas" +
      "hAvailSubType\030\004 \001(\t\022\025\n\rknowledgeDate\030\005 \001" +
      "(\t\022\025\n\reffectiveDate\030\006 \001(\t\022\020\n\010currency\030\007 " +
      "\001(\t\022\016\n\006amount\030\010 \001(\001\"\007\n\005Empty2<\n\tcashAvai" +
      "l\022/\n\014getCashAvail\022\021.CashAvailRequest\032\014.A" +
      "PIResponseB\021\n\017com.drifai.grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CashAvailRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CashAvailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CashAvailRequest_descriptor,
        new java.lang.String[] { "FundId", "CashAvailType", "CashAvailSubType", "Currency", });
    internal_static_APIResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_APIResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_APIResponse_descriptor,
        new java.lang.String[] { "ClientId", "FundId", "CashAvailType", "CashAvailSubType", "KnowledgeDate", "EffectiveDate", "Currency", "Amount", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
